import { fromPairs } from 'lodash'

export { default as HeroCustom } from './hero-custom'
export { default as Services } from './services'
export { default as Overview } from './overview'
export { default as ImageRight } from './image-right'
export { default as WhatAreStrategicCommunications } from './what-are-strategic-communications'
export { default as ImageRightSmallImageDetachedTitle } from './image-right-small-image-detached-title'
export { default as DefaultCentered } from './default-centered'
export { default as ImageLeft } from './image-left'
export { default as Hero } from './hero'
export { default as HeroContact} from './hero-contact'
export { default as Default } from './default'